<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Eatery;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $marketId = 18; // Chợ Trung Tâm Đông Anh

        // 1. Cập nhật thông tin Chợ Trung Tâm Đông Anh trong eateries
        DB::table('eateries')->where('id', $marketId)->update([
            'name' => 'Chợ Trung Tâm Đông Anh',
            'category_id' => 8, // Chợ truyền thống
            'address' => '4VP4+V46, Thị trấn Đông Anh, Huyện Đông Anh, Hà Nội',
            'updated_at' => now(),
        ]);

        // 2. Tạo / Cập nhật tài khoản Ban Quản lý Chợ Trung Tâm
        $bql = User::where('email', 'bql.chotrungtam@foodmap.vn')->first();
        if (!$bql) {
            DB::table('users')->insert([
                'name' => 'Ban Quản lý Chợ Trung Tâm Đông Anh',
                'email' => 'bql.chotrungtam@foodmap.vn',
                'phone' => '0123654999',
                'password' => Hash::make('123456@'),
                'role' => 'seller',
                'status' => 'active',
                'eatery_id' => $marketId,
                'avatar' => '🏛️',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        } else {
            $bql->update([
                'name' => 'Ban Quản lý Chợ Trung Tâm Đông Anh',
                'eatery_id' => $marketId,
                'role' => 'seller',
                'status' => 'active',
            ]);
        }

        // 3. Danh sách 118 hộ kinh doanh Chợ Trung Tâm từ Excel
        $merchants = array (
  1 => 
  array (
    'stt' => 1,
    'name' => 'Nguyễn Thị Ngà( Thanh)',
    'birth_date' => '29806',
    'address' => '',
    'cccd' => '001181012763',
    'issue_date' => '16/09/2022',
    'phone' => '',
    'category' => 'Hoa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  2 => 
  array (
    'stt' => 2,
    'name' => 'Nguyễn Thị Thanh Huyền',
    'birth_date' => '21/04/1993',
    'address' => '',
    'cccd' => '001193035279',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hoa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  3 => 
  array (
    'stt' => 3,
    'name' => 'Trịnh Thị Hương',
    'birth_date' => '30/10/1983',
    'address' => '',
    'cccd' => '001183045096',
    'issue_date' => '16/052022',
    'phone' => '',
    'category' => 'Hoa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  4 => 
  array (
    'stt' => 4,
    'name' => 'Phạm Thị Nhung',
    'birth_date' => '13/10/1977',
    'address' => '',
    'cccd' => '026177015328',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  5 => 
  array (
    'stt' => 5,
    'name' => 'Phạm Thị Phượng',
    'birth_date' => '21917',
    'address' => '',
    'cccd' => '001160039660',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  6 => 
  array (
    'stt' => 6,
    'name' => 'Trần Thị Ngần',
    'birth_date' => '14/10/1970',
    'address' => '',
    'cccd' => '001170018875',
    'issue_date' => '19/08/2021',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  7 => 
  array (
    'stt' => 7,
    'name' => 'Đặng Thúy Hằng',
    'birth_date' => '21/01/1978',
    'address' => '',
    'cccd' => '036178000152',
    'issue_date' => '24/07/2021',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  8 => 
  array (
    'stt' => 8,
    'name' => 'Hoàng Thị Loan',
    'birth_date' => '19/4/1976',
    'address' => '',
    'cccd' => '001176045857',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  9 => 
  array (
    'stt' => 9,
    'name' => 'Nguyễn Thị Nên',
    'birth_date' => '23775',
    'address' => '',
    'cccd' => '030165006299',
    'issue_date' => '45932',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  10 => 
  array (
    'stt' => 10,
    'name' => 'Nguyễn Thị Thu',
    'birth_date' => '26/01/1981',
    'address' => '',
    'cccd' => '001181012979',
    'issue_date' => '44473',
    'phone' => '',
    'category' => 'Chè nước',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  11 => 
  array (
    'stt' => 11,
    'name' => 'Nguyễn Thị Thùy',
    'birth_date' => '23411',
    'address' => '',
    'cccd' => '001164006581',
    'issue_date' => '15/04/2022',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  12 => 
  array (
    'stt' => 12,
    'name' => 'Đinh Thị Thanh Huyền',
    'birth_date' => '28501',
    'address' => '',
    'cccd' => '001178019316',
    'issue_date' => '15/08/2022',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  13 => 
  array (
    'stt' => 13,
    'name' => 'Bùi Thị Thơ',
    'birth_date' => '25204',
    'address' => '',
    'cccd' => '030169015922',
    'issue_date' => '44477',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  14 => 
  array (
    'stt' => 14,
    'name' => 'Lê Thị Mý',
    'birth_date' => '26665',
    'address' => '',
    'cccd' => '001173006071',
    'issue_date' => '21/8/2022',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  15 => 
  array (
    'stt' => 15,
    'name' => 'Ngô Thị Thu',
    'birth_date' => '23870',
    'address' => '',
    'cccd' => '001165011629',
    'issue_date' => '27/02/2025',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  16 => 
  array (
    'stt' => 16,
    'name' => 'Lê Thị Hạnh',
    'birth_date' => '6/6/1965',
    'address' => '',
    'cccd' => '001165009459',
    'issue_date' => '26/02/2025',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  17 => 
  array (
    'stt' => 17,
    'name' => 'Đinh Thị Hồng Hạnh',
    'birth_date' => '28501',
    'address' => '',
    'cccd' => '001178013132',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  18 => 
  array (
    'stt' => 18,
    'name' => 'Đỗ Thị Mùi',
    'birth_date' => '20249',
    'address' => '',
    'cccd' => '001155006981',
    'issue_date' => '44444',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  19 => 
  array (
    'stt' => 19,
    'name' => 'Hoàng Thị Tú',
    'birth_date' => '29231',
    'address' => '',
    'cccd' => '001180042597',
    'issue_date' => '24/07/2021',
    'phone' => '',
    'category' => 'vịt quay',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  20 => 
  array (
    'stt' => 20,
    'name' => 'Nguyễn Thị Quế',
    'birth_date' => '17/12/1983',
    'address' => '',
    'cccd' => '001183052233',
    'issue_date' => '30/05/2023',
    'phone' => '',
    'category' => 'ăn chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  21 => 
  array (
    'stt' => 21,
    'name' => 'Nguyễn Thị Lệ Huyền',
    'birth_date' => '28949',
    'address' => '',
    'cccd' => '025179000998',
    'issue_date' => '24/07/2021',
    'phone' => '',
    'category' => 'ăn chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  22 => 
  array (
    'stt' => 22,
    'name' => 'Trịnh Thị Lan',
    'birth_date' => '28311',
    'address' => '',
    'cccd' => '001177015988',
    'issue_date' => '16/05/2022',
    'phone' => '',
    'category' => 'ăn chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  23 => 
  array (
    'stt' => 23,
    'name' => 'Ngô Thành Huế',
    'birth_date' => '31017',
    'address' => '',
    'cccd' => '001184050991',
    'issue_date' => '19/04/2023',
    'phone' => '',
    'category' => 'ăn chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  24 => 
  array (
    'stt' => 24,
    'name' => 'Tạ Thị Hậu',
    'birth_date' => '19360',
    'address' => '',
    'cccd' => '001153019526',
    'issue_date' => '14/06/2023',
    'phone' => '',
    'category' => 'ăn chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  25 => 
  array (
    'stt' => 25,
    'name' => 'Nguyễn Thúy Hằng',
    'birth_date' => '27737',
    'address' => '',
    'cccd' => '001175024183',
    'issue_date' => '24/07/2021',
    'phone' => '',
    'category' => 'Đậu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  26 => 
  array (
    'stt' => 26,
    'name' => 'Trần Văn Đại',
    'birth_date' => '22/01/1969',
    'address' => '',
    'cccd' => '001069025030',
    'issue_date' => '25/04/2021',
    'phone' => '',
    'category' => 'Đậu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  27 => 
  array (
    'stt' => 27,
    'name' => 'Nguyễn Đăng Chính',
    'birth_date' => '31904',
    'address' => '',
    'cccd' => '027087013308',
    'issue_date' => '15/08/2022',
    'phone' => '',
    'category' => 'Đậu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  28 => 
  array (
    'stt' => 28,
    'name' => 'Lê Thị Lý( Lê Thị Núi)',
    'birth_date' => '27395',
    'address' => '',
    'cccd' => '001175044718',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  29 => 
  array (
    'stt' => 29,
    'name' => 'Đặng Thị Thúy',
    'birth_date' => '28035',
    'address' => '',
    'cccd' => '024176005413',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Măng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  30 => 
  array (
    'stt' => 30,
    'name' => 'Đào Thị Phượng',
    'birth_date' => '18/07/1987',
    'address' => '',
    'cccd' => '001187037429',
    'issue_date' => '19/4/2021',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  31 => 
  array (
    'stt' => 31,
    'name' => 'Hoàng Thị Nở',
    'birth_date' => '25843',
    'address' => '',
    'cccd' => '038170000129',
    'issue_date' => '45483',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  32 => 
  array (
    'stt' => 32,
    'name' => 'Nguyễn Thị Huyền',
    'birth_date' => '30174',
    'address' => '',
    'cccd' => '001182033524',
    'issue_date' => '23/12/2022',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  33 => 
  array (
    'stt' => 33,
    'name' => 'Nguyễn Thị Nhung',
    'birth_date' => '25204',
    'address' => '',
    'cccd' => '001169042060',
    'issue_date' => '22/11/2021',
    'phone' => '',
    'category' => 'Cua xay',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  34 => 
  array (
    'stt' => 34,
    'name' => 'Ngô Thị Nụ',
    'birth_date' => '18/02/1961',
    'address' => '',
    'cccd' => '030161013647',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  35 => 
  array (
    'stt' => 35,
    'name' => 'Hoàng Thị Ngoan',
    'birth_date' => '15/05/1962',
    'address' => '',
    'cccd' => '001162042030',
    'issue_date' => '44205',
    'phone' => '',
    'category' => 'chanh, tỏi',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  36 => 
  array (
    'stt' => 36,
    'name' => 'Trần Thị Thao',
    'birth_date' => '308/3/1958',
    'address' => '',
    'cccd' => '035158002182',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  37 => 
  array (
    'stt' => 37,
    'name' => 'Tô Quốc Dậu',
    'birth_date' => '27/10/1969',
    'address' => '',
    'cccd' => '001069000953',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  38 => 
  array (
    'stt' => 38,
    'name' => 'Nguyễn Thị Nhuận',
    'birth_date' => '27760',
    'address' => '',
    'cccd' => '001176022801',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  39 => 
  array (
    'stt' => 39,
    'name' => 'Trần Văn Thủy',
    'birth_date' => '20/10/1959',
    'address' => '',
    'cccd' => '001059029180',
    'issue_date' => '16/08/2021',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  40 => 
  array (
    'stt' => 40,
    'name' => 'Phạm Thị Bách',
    'birth_date' => '28529',
    'address' => '',
    'cccd' => '019178000389',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  41 => 
  array (
    'stt' => 41,
    'name' => 'Trần Đình Thủy (Thảo)',
    'birth_date' => '25/06/1965',
    'address' => '',
    'cccd' => '001065015298',
    'issue_date' => '25/4/2021',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  42 => 
  array (
    'stt' => 42,
    'name' => 'Trần Văn Hòa',
    'birth_date' => '23/2/1971',
    'address' => '',
    'cccd' => '001071002513',
    'issue_date' => '44658',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  43 => 
  array (
    'stt' => 43,
    'name' => 'Nguyễn Thị Xuyến',
    'birth_date' => '20455',
    'address' => '',
    'cccd' => '001156010903',
    'issue_date' => '27/4/2021',
    'phone' => '',
    'category' => 'Gia cầm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  44 => 
  array (
    'stt' => 44,
    'name' => 'Hoàng Ngọc Lâm',
    'birth_date' => '29/10/1969',
    'address' => '',
    'cccd' => '001069037711',
    'issue_date' => '24/06/2021',
    'phone' => '',
    'category' => 'Hải sản',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  45 => 
  array (
    'stt' => 45,
    'name' => 'Phạm Thị Tú',
    'birth_date' => '20/02/1960',
    'address' => '',
    'cccd' => '001160004025',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Cá',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  46 => 
  array (
    'stt' => 46,
    'name' => 'Trần Thị Kiều Trang ( Mai)',
    'birth_date' => '31787',
    'address' => '',
    'cccd' => '001187025267',
    'issue_date' => '44813',
    'phone' => '',
    'category' => 'Cua xay',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  47 => 
  array (
    'stt' => 47,
    'name' => 'Nguyễn Thị Thoan',
    'birth_date' => '25/12/1969',
    'address' => '',
    'cccd' => '001169016063',
    'issue_date' => '44201',
    'phone' => '',
    'category' => 'Tôm cá',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  48 => 
  array (
    'stt' => 48,
    'name' => 'Diệp Thị Phượng',
    'birth_date' => '24/12/1982',
    'address' => '',
    'cccd' => '019182000305',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Cá',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  49 => 
  array (
    'stt' => 49,
    'name' => 'Nguyễn Thị Dự',
    'birth_date' => '24473',
    'address' => '',
    'cccd' => '001167029819',
    'issue_date' => '20/7/2021',
    'phone' => '',
    'category' => 'Cá',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  50 => 
  array (
    'stt' => 50,
    'name' => 'Trần Thị Nền',
    'birth_date' => '21/3/1982',
    'address' => '',
    'cccd' => '001182009423',
    'issue_date' => '44474',
    'phone' => '',
    'category' => 'Cá',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  51 => 
  array (
    'stt' => 51,
    'name' => 'Đồng Thị Ninh',
    'birth_date' => '25/7/1978',
    'address' => '',
    'cccd' => '001178005532',
    'issue_date' => '44444',
    'phone' => '',
    'category' => 'Khoai, lạc chín',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  52 => 
  array (
    'stt' => 52,
    'name' => 'Ngô Thị Mùi',
    'birth_date' => '14/07/1975',
    'address' => '',
    'cccd' => '019175007977',
    'issue_date' => '44476',
    'phone' => '',
    'category' => 'Bánh',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  53 => 
  array (
    'stt' => 53,
    'name' => 'Nguyễn Thị Dung',
    'birth_date' => '23530',
    'address' => '',
    'cccd' => '001164029637',
    'issue_date' => '44382',
    'phone' => '',
    'category' => 'Bánh',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  54 => 
  array (
    'stt' => 54,
    'name' => 'Hoàng Thị Duy',
    'birth_date' => '26308',
    'address' => '',
    'cccd' => '001172012483',
    'issue_date' => '44382',
    'phone' => '',
    'category' => 'SC quần áo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  55 => 
  array (
    'stt' => 55,
    'name' => 'Hoàng Thị Quỳnh',
    'birth_date' => '20/1/1981',
    'address' => '',
    'cccd' => '001181020187',
    'issue_date' => '24/4/2021',
    'phone' => '',
    'category' => 'SC quần áo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  56 => 
  array (
    'stt' => 56,
    'name' => 'Vũ Thị Tuyên',
    'birth_date' => '30/6/1954',
    'address' => '',
    'cccd' => '035154002006',
    'issue_date' => '44444',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  57 => 
  array (
    'stt' => 57,
    'name' => 'Hoàng Thị Duyên',
    'birth_date' => '27/2/1988',
    'address' => '',
    'cccd' => '001188019569',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Gia dụng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  58 => 
  array (
    'stt' => 58,
    'name' => 'Lương Thị Tho',
    'birth_date' => '21186',
    'address' => '',
    'cccd' => '001158012806',
    'issue_date' => '44444',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  59 => 
  array (
    'stt' => 59,
    'name' => 'Ngô Thị Khuy',
    'birth_date' => '29953',
    'address' => '',
    'cccd' => '001182025774',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Bánh quấn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  60 => 
  array (
    'stt' => 60,
    'name' => 'Nguyễn Thị Thuật',
    'birth_date' => '28493',
    'address' => '',
    'cccd' => '001178037819',
    'issue_date' => '27/9/2021',
    'phone' => '',
    'category' => 'Rau',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  61 => 
  array (
    'stt' => 61,
    'name' => 'Trần Thị Hải',
    'birth_date' => '25204',
    'address' => '',
    'cccd' => '001169008722',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  62 => 
  array (
    'stt' => 62,
    'name' => 'Đồng Thị Nự',
    'birth_date' => '23012',
    'address' => '',
    'cccd' => '001163032315',
    'issue_date' => '45085',
    'phone' => '',
    'category' => 'Bánh quấn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  63 => 
  array (
    'stt' => 63,
    'name' => 'Phạm Văn Sơn',
    'birth_date' => '15/6/1969',
    'address' => '',
    'cccd' => '038069002819',
    'issue_date' => '24/7/2021',
    'phone' => '',
    'category' => 'Hải sản',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  64 => 
  array (
    'stt' => 64,
    'name' => 'Nguyễn Thị Nụ',
    'birth_date' => '17/6/1994',
    'address' => '',
    'cccd' => '001194036582',
    'issue_date' => '44693',
    'phone' => '',
    'category' => 'Quả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  65 => 
  array (
    'stt' => 65,
    'name' => 'Nguyễn Thị Ánh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  66 => 
  array (
    'stt' => 66,
    'name' => 'Đỗ Thị Ngọc Anh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt gà',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  67 => 
  array (
    'stt' => 67,
    'name' => 'Nguyễn Thị Chuyên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  68 => 
  array (
    'stt' => 68,
    'name' => 'Nguyễn Thị Hường',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  69 => 
  array (
    'stt' => 69,
    'name' => 'Lê Thị Hạ',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt bò',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  70 => 
  array (
    'stt' => 70,
    'name' => 'Trần Thị Diện',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  71 => 
  array (
    'stt' => 71,
    'name' => 'Trịnh Thị Lý',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  72 => 
  array (
    'stt' => 72,
    'name' => 'Nguyễn Thị Luân',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  73 => 
  array (
    'stt' => 73,
    'name' => 'Nguyễn Thị Thanh Tâm',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  74 => 
  array (
    'stt' => 74,
    'name' => 'Hoàng Thị Thúy Vân',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  75 => 
  array (
    'stt' => 75,
    'name' => 'Đặng Thị Định',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  76 => 
  array (
    'stt' => 76,
    'name' => 'Lê Đức Tư',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  77 => 
  array (
    'stt' => 77,
    'name' => 'Nguyễn Thị Quyên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  78 => 
  array (
    'stt' => 78,
    'name' => 'Nguyễn Thị Bắc',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  79 => 
  array (
    'stt' => 79,
    'name' => 'Nguyễn Thị Thi ( Minh)',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  80 => 
  array (
    'stt' => 80,
    'name' => 'Nguyễn Thị Thu',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt bò',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  81 => 
  array (
    'stt' => 81,
    'name' => 'Nguyễn Thị Hồng Hải',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  82 => 
  array (
    'stt' => 82,
    'name' => 'Nguyễn Thị Tươi',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt bò',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  83 => 
  array (
    'stt' => 83,
    'name' => 'Ngô Thị Tiến',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  84 => 
  array (
    'stt' => 84,
    'name' => 'Đinh Thị Vân',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  85 => 
  array (
    'stt' => 85,
    'name' => 'Nguyễn Thị Luyên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  86 => 
  array (
    'stt' => 86,
    'name' => 'Nguyễn Thị Mai',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Thịt lợn',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  87 => 
  array (
    'stt' => 87,
    'name' => 'Bùi Thị Dung',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hải sản',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  88 => 
  array (
    'stt' => 88,
    'name' => 'Nguyễn Thị Lan',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Giò chả',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  89 => 
  array (
    'stt' => 89,
    'name' => 'Nguyễn Thị Lệ Hường',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  90 => 
  array (
    'stt' => 90,
    'name' => 'Trần Văn Dương',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Cắt tóc',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  91 => 
  array (
    'stt' => 91,
    'name' => 'Nguyễn Thị Thủy',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gội đầu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  92 => 
  array (
    'stt' => 92,
    'name' => 'Đỗ Thị Lương',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gội đầu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  93 => 
  array (
    'stt' => 93,
    'name' => 'Thái Thị Hương',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Phụ kiện',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  94 => 
  array (
    'stt' => 94,
    'name' => 'Nguyễn Văn Thái',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa bánh kẹo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  95 => 
  array (
    'stt' => 95,
    'name' => 'Lê Thị Thu Nga',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  96 => 
  array (
    'stt' => 96,
    'name' => 'Trần Thị Kim Oanh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gia dụng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  97 => 
  array (
    'stt' => 97,
    'name' => 'Nguyễn Thị Xuân Thu',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gia dụng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  98 => 
  array (
    'stt' => 98,
    'name' => 'Hoàng Thị Liên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gội đầu',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  99 => 
  array (
    'stt' => 99,
    'name' => 'Nguyễn Thị Phương Mai',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa bánh kẹo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  100 => 
  array (
    'stt' => 100,
    'name' => 'Ngô Thị Hương',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa bánh kẹo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  101 => 
  array (
    'stt' => 101,
    'name' => 'Phạm Thị Thu Thủy',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  102 => 
  array (
    'stt' => 102,
    'name' => 'Nguyễn Thị Tường',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  103 => 
  array (
    'stt' => 103,
    'name' => 'Nguyễn Thị Giang',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  104 => 
  array (
    'stt' => 104,
    'name' => 'Vương Thị Quyên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  105 => 
  array (
    'stt' => 105,
    'name' => 'Hoàng Thị Lệ Hằng',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  106 => 
  array (
    'stt' => 106,
    'name' => 'Lê Thị Hiên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  107 => 
  array (
    'stt' => 107,
    'name' => 'Nguyễn Thị Mùi',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Hàng khô',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  108 => 
  array (
    'stt' => 108,
    'name' => 'Trần Thị Kim Thanh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Gia dụng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  109 => 
  array (
    'stt' => 109,
    'name' => 'Hoàng Thị Thu Trang',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Bún mộc, cơm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  110 => 
  array (
    'stt' => 110,
    'name' => 'Nguyễn Thị Hoa',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Quần áo',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  111 => 
  array (
    'stt' => 111,
    'name' => 'Nguyễn Thị Ánh Hồng',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Phở gà',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  112 => 
  array (
    'stt' => 112,
    'name' => 'Nguyễn Thị Nhượng',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Bách hóa tổng hợp',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  113 => 
  array (
    'stt' => 113,
    'name' => 'Nguyễn Vân Anh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Bún cá rô đồng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  114 => 
  array (
    'stt' => 114,
    'name' => 'Nguyễn Văn Nguyên',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Cơm',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  115 => 
  array (
    'stt' => 115,
    'name' => 'Tô Thị Mai Thanh',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Ăn vặt',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  116 => 
  array (
    'stt' => 116,
    'name' => 'Nguyễn Huyền Trang',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Tạp hóa',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  117 => 
  array (
    'stt' => 117,
    'name' => 'Nguyễn Trung Thành',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Văn phòng',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
  118 => 
  array (
    'stt' => 118,
    'name' => 'Vương Văn Quyền',
    'birth_date' => '',
    'address' => '',
    'cccd' => '',
    'issue_date' => '',
    'phone' => '',
    'category' => 'Cà phê',
    'bank_account' => '',
    'qr_note' => '',
    'note' => '',
  ),
);

        // Xóa toàn bộ sạp cũ thuộc Chợ Trung Tâm để nạp lại chuẩn xác 118 sạp
        DB::table('ocop_products')->where('eatery_id', $marketId)->delete();

        foreach ($merchants as $stt => $m) {
            $stallId = 1937 + $stt;
            $email = "seller.trungTam.{$stt}@foodmap.vn";
            $phone = $m['phone'] ?: '';
            $name = $m['name'] ?: "Hộ kinh doanh số {$stt}";
            $cat = $m['category'] ?: 'Bách hóa tổng hợp';

            // Tạo mã QR VietQR nếu có số điện thoại
            $hasPhone = !empty($phone);
            $bankName = $hasPhone ? 'MBBank' : null;
            $bankAccount = $hasPhone ? $phone : null;
            $qrUrl = $hasPhone ? "https://api.vietqr.io/image/970422-{$phone}-compact.png?accountName=" . urlencode($name) : null;

            // Xử lý tạo / cập nhật User
            $user = User::where('email', $email)->first();

            if (!$user) {
                $userId = DB::table('users')->insertGetId([
                    'name' => $name,
                    'email' => $email,
                    'phone' => $phone ?: 'Cần cập nhật thông tin',
                    'password' => Hash::make('123456@'),
                    'role' => 'seller',
                    'status' => 'active',
                    'eatery_id' => $marketId,
                    'stall_id' => $stallId,
                    'bank_name' => $bankName,
                    'bank_account' => $bankAccount,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            } else {
                $user->update([
                    'name' => $name,
                    'email' => $email,
                    'phone' => $phone ?: 'Cần cập nhật thông tin',
                    'role' => 'seller',
                    'status' => 'active',
                    'eatery_id' => $marketId,
                    'stall_id' => $stallId,
                    'bank_name' => $bankName,
                    'bank_account' => $bankAccount,
                ]);
                $userId = $user->id;
            }

            // Xử lý tạo Gian hàng với stall_name duy nhất
            $stallName = "Gian hàng " . $cat . " " . $name . " (Hộ {$stt})";
            $descParts = [];
            if (!empty($m['address'])) $descParts[] = "Địa chỉ: " . $m['address'];
            if (!empty($m['birth_date'])) $descParts[] = "Ngày sinh: " . $m['birth_date'];
            if (!empty($m['cccd'])) $descParts[] = "CCCD: " . $m['cccd'] . (!empty($m['issue_date']) ? " (Cấp: {$m['issue_date']})" : "");
            $desc = !empty($descParts) ? implode(' | ', $descParts) : "Hộ kinh doanh tại Chợ Trung Tâm Đông Anh";

            DB::table('ocop_products')->insert([
                'id' => $stallId,
                'eatery_id' => $marketId,
                'user_id' => $userId,
                'stall_name' => $stallName,
                'name' => $cat,
                'seller_name' => $name,
                'seller_phone' => $phone ?: 'Cần cập nhật thông tin',
                'description' => $desc,
                'bank_name' => $bankName,
                'bank_account' => $bankAccount,
                'bank_holder' => $hasPhone ? $name : null,
                'qr_code_path' => $qrUrl,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
    }
};
