<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Eatery;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $marketId = 30; // Chợ Dày Da / Giầy Da

        // 1. Cập nhật thông tin Chợ Dày Da trong eateries
        DB::table('eateries')->where('id', $marketId)->update([
            'name' => 'Chợ Dày Da',
            'category_id' => 8, // Chợ truyền thống
            'address' => 'Thôn Dục Nội, Xã Việt Hùng, Huyện Đông Anh, Hà Nội',
            'updated_at' => now(),
        ]);

        // 2. Tạo / Cập nhật tài khoản Ban Quản lý Chợ Dày Da
        $bql = User::where('email', 'bql.chodayda@foodmap.vn')->orWhere('email', 'bql.choDayDa@foodmap.vn')->first();
        if (!$bql) {
            DB::table('users')->insert([
                'name' => 'Ban Quản lý Chợ Dày Da (Nguyễn Đình Trung)',
                'email' => 'bql.chodayda@foodmap.vn',
                'phone' => '0123654030',
                'password' => Hash::make('123456@'),
                'role' => 'seller',
                'status' => 'active',
                'eatery_id' => $marketId,
                'avatar' => '🏛️',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        } else {
            $bql->update([
                'name' => 'Ban Quản lý Chợ Dày Da (Nguyễn Đình Trung)',
                'email' => 'bql.chodayda@foodmap.vn',
                'phone' => '0123654030',
                'eatery_id' => $marketId,
                'role' => 'seller',
                'status' => 'active',
            ]);
        }

        // 3. Xóa các tài khoản trùng lặp và tài khoản rác cũ
        $sellerEmailsToKeep = ['bql.chodayda@foodmap.vn'];
        for ($i = 1; $i <= 107; $i++) {
            $sellerEmailsToKeep[] = "seller.dayDa.{$i}@foodmap.vn";
        }
        User::where('eatery_id', $marketId)
            ->where(function($q) use ($sellerEmailsToKeep) {
                $q->whereNotIn('email', $sellerEmailsToKeep)->orWhereNull('email')->orWhere('email', '');
            })
            ->delete();

        // 4. Danh sách 107 hộ kinh doanh chuẩn từ Excel
        $merchants = array (
  1 => 
  array (
    'stt' => 1,
    'name' => 'Trương Thu Hương',
    'stall_name' => 'Gian hàng Bánh Cuốn Trương Thu Hương (Hộ 1)',
    'item_name' => 'Bánh cuốn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Bắc Ninh',
    'phone' => '0972167170',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  2 => 
  array (
    'stt' => 2,
    'name' => 'Đình Thị Thoa',
    'stall_name' => 'Gian hàng Bánh Cuốn Đình Thị Thoa (Hộ 2)',
    'item_name' => 'Bánh cuốn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Bắc Ninh',
    'phone' => '0393709671',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  3 => 
  array (
    'stt' => 3,
    'name' => 'Nguyễn Thị Ngọc Bích',
    'stall_name' => 'Gian hàng Nước Mía Nguyễn Thị Ngọc Bích (Hộ 3)',
    'item_name' => 'nước mía',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '096458093',
    'bank_name' => 'MBBank',
    'bank_account' => '41932277',
    'qr_bin' => '970422',
  ),
  4 => 
  array (
    'stt' => 4,
    'name' => 'Nguyễn Thị Oanh',
    'stall_name' => 'Gian hàng Bún, Nước Trà Đá Nguyễn Thị Oanh (Hộ 4)',
    'item_name' => 'bún, nước trà đá',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0352299258',
    'bank_name' => 'MBBank',
    'bank_account' => '442548868',
    'qr_bin' => '970422',
  ),
  5 => 
  array (
    'stt' => 5,
    'name' => 'Lê Anh Quân',
    'stall_name' => 'Gian hàng Bánh Cá, Café Lê Anh Quân (Hộ 5)',
    'item_name' => 'bánh cá, café',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Mua online',
    'phone' => '0983640985',
    'bank_name' => 'MB Bank',
    'bank_account' => '4612006916088',
    'qr_bin' => '970422',
  ),
  6 => 
  array (
    'stt' => 6,
    'name' => 'Nguyễn Thị Lệ',
    'stall_name' => 'Gian hàng Nước Mía, Nước Dừa Nguyễn Thị Lệ (Hộ 6)',
    'item_name' => 'nước mía, nước dừa',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0964882273',
    'bank_name' => 'MBBank',
    'bank_account' => '090001060003936',
    'qr_bin' => '970422',
  ),
  7 => 
  array (
    'stt' => 7,
    'name' => 'Đặng Thị Thêm',
    'stall_name' => 'Gian hàng Nước Mía, Nước Dừa Đặng Thị Thêm (Hộ 7)',
    'item_name' => 'nước mía, nước dừa',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Tại nơi bán hàng',
    'phone' => '0369788501',
    'bank_name' => 'MBBank',
    'bank_account' => '030301818',
    'qr_bin' => '970422',
  ),
  8 => 
  array (
    'stt' => 8,
    'name' => 'Ngô Thị Lan',
    'stall_name' => 'Gian hàng Quần Áo Ngô Thị Lan (Hộ 8)',
    'item_name' => 'quần áo',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Ninh Hiệp, chợ Đồng Xuân',
    'phone' => '0988446427',
    'bank_name' => 'VP Bank',
    'bank_account' => '569950864',
    'qr_bin' => '970432',
  ),
  9 => 
  array (
    'stt' => 9,
    'name' => 'Trần Thị Hằng',
    'stall_name' => 'Gian hàng Quần Áo Trần Thị Hằng (Hộ 9)',
    'item_name' => 'quần áo',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Ninh Hiệp',
    'phone' => '0373399588',
    'bank_name' => 'VP Bank',
    'bank_account' => '0373399588',
    'qr_bin' => '970432',
  ),
  10 => 
  array (
    'stt' => 10,
    'name' => 'Nguyễn Đình Bắc',
    'stall_name' => 'Gian hàng Bia Hơi Hà Nội Nguyễn Đình Bắc (Hộ 10)',
    'item_name' => 'bia hơi Hà Nội',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà máy bia Hà Nội',
    'phone' => '0982238940',
    'bank_name' => 'Techcombank',
    'bank_account' => '19038937832018',
    'qr_bin' => '970422',
  ),
  11 => 
  array (
    'stt' => 11,
    'name' => 'Vũ Thị Hà',
    'stall_name' => 'Gian hàng Thịt Chó Và Bán Bún Vũ Thị Hà (Hộ 11)',
    'item_name' => 'thịt chó và bán bún',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Mua của dân',
    'phone' => '0964688482',
    'bank_name' => 'MB Bank',
    'bank_account' => '4214052009',
    'qr_bin' => '970422',
  ),
  12 => 
  array (
    'stt' => 12,
    'name' => 'Trần Văn Tiến',
    'stall_name' => 'Gian hàng Hoa Quả Trần Văn Tiến (Hộ 12)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0833722573',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  13 => 
  array (
    'stt' => 13,
    'name' => 'Phạm Văn Hưng',
    'stall_name' => 'Gian hàng Xôi Phạm Văn Hưng (Hộ 13)',
    'item_name' => 'xôi',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn - Bắc Ninh',
    'phone' => '0965270881',
    'bank_name' => 'BIDV',
    'bank_account' => '2143493184',
    'qr_bin' => '970418',
  ),
  14 => 
  array (
    'stt' => 14,
    'name' => 'Nguyễn Thị Hằng',
    'stall_name' => 'Gian hàng Hoa Quả Nguyễn Thị Hằng (Hộ 14)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0384669969',
    'bank_name' => 'Vietcombank',
    'bank_account' => '0821000071781',
    'qr_bin' => '970436',
  ),
  15 => 
  array (
    'stt' => 15,
    'name' => 'Công Thị Tài',
    'stall_name' => 'Gian hàng Rau Quả Công Thị Tài (Hộ 15)',
    'item_name' => 'rau quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội - Đông Anh',
    'phone' => '0383948886',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  16 => 
  array (
    'stt' => 16,
    'name' => 'Lê Thị Bình',
    'stall_name' => 'Gian hàng Rau Củ Quả Lê Thị Bình (Hộ 16)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Xã Vĩnh Thanh',
    'phone' => '0963678385',
    'bank_name' => 'MB Bank',
    'bank_account' => '91119858888',
    'qr_bin' => '970422',
  ),
  17 => 
  array (
    'stt' => 17,
    'name' => 'Nguyễn Thị Anh Trang',
    'stall_name' => 'Gian hàng Hoa Quả Nguyễn Thị Anh Trang (Hộ 17)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0979427943',
    'bank_name' => 'MB Bank',
    'bank_account' => '0979427953',
    'qr_bin' => '970422',
  ),
  18 => 
  array (
    'stt' => 18,
    'name' => 'Lê Văn Tuy',
    'stall_name' => 'Gian hàng Chuối Chín Lê Văn Tuy (Hộ 18)',
    'item_name' => 'chuối chín',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Tỉnh Hưng Yên',
    'phone' => '0974433821',
    'bank_name' => 'BIDV',
    'bank_account' => '2141512782',
    'qr_bin' => '970418',
  ),
  19 => 
  array (
    'stt' => 19,
    'name' => 'Nguyễn Việt',
    'stall_name' => 'Gian hàng Hoa Quả Nguyễn Việt (Hộ 19)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Vĩnh Phúc',
    'phone' => '0866486447',
    'bank_name' => 'MB Bank',
    'bank_account' => '0866486447',
    'qr_bin' => '970422',
  ),
  20 => 
  array (
    'stt' => 20,
    'name' => 'Lê Thị Vân',
    'stall_name' => 'Gian hàng Dưa Hấu Lê Thị Vân (Hộ 20)',
    'item_name' => 'dưa hấu',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Từ Sơn - Bắc Ninh',
    'phone' => '0974524571',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  21 => 
  array (
    'stt' => 21,
    'name' => 'Nguyễn Thị Cúc',
    'stall_name' => 'Gian hàng Rau Quả Nguyễn Thị Cúc (Hộ 21)',
    'item_name' => 'rau quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '0334042560',
    'bank_name' => 'Techcombank',
    'bank_account' => '2411786666',
    'qr_bin' => '970422',
  ),
  22 => 
  array (
    'stt' => 22,
    'name' => 'Lê Thị Oanh',
    'stall_name' => 'Gian hàng Hoa Quả Lê Thị Oanh (Hộ 22)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0362762488',
    'bank_name' => 'MBBank',
    'bank_account' => '080362762488',
    'qr_bin' => '970422',
  ),
  23 => 
  array (
    'stt' => 23,
    'name' => 'Hữu Thị Hoa',
    'stall_name' => 'Gian hàng Rau Hữu Thị Hoa (Hộ 23)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng, chợ Dục Nội',
    'phone' => '0984725053',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  24 => 
  array (
    'stt' => 24,
    'name' => 'Nguyễn Thị Lý',
    'stall_name' => 'Gian hàng Bún Sợi, Bánh Mỳ Nguyễn Thị Lý (Hộ 24)',
    'item_name' => 'bún sợi, bánh mỳ',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Làng Vân',
    'phone' => '0364711975',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  25 => 
  array (
    'stt' => 25,
    'name' => 'Trí Thị Tuyết',
    'stall_name' => 'Gian hàng Cháo Trai Trí Thị Tuyết (Hộ 25)',
    'item_name' => 'cháo trai',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '0983399572',
    'bank_name' => 'MBBank',
    'bank_account' => '0983399572',
    'qr_bin' => '970422',
  ),
  26 => 
  array (
    'stt' => 26,
    'name' => 'Phạm Thị Lan',
    'stall_name' => 'Gian hàng Nước Mía, Trà Đá Phạm Thị Lan (Hộ 26)',
    'item_name' => 'nước mía, trà đá',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhập tại nhà',
    'phone' => '0983159736',
    'bank_name' => 'BIDV',
    'bank_account' => '2140604996',
    'qr_bin' => '970418',
  ),
  27 => 
  array (
    'stt' => 27,
    'name' => 'Dương Thị Nụ',
    'stall_name' => 'Gian hàng Trứng Dương Thị Nụ (Hộ 27)',
    'item_name' => 'trứng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Sóc Sơn, Thư Lâm',
    'phone' => '0364158027',
    'bank_name' => 'MB Bank',
    'bank_account' => '0364158027',
    'qr_bin' => '970422',
  ),
  28 => 
  array (
    'stt' => 28,
    'name' => 'Cao Thị Huệ',
    'stall_name' => 'Gian hàng Rau Cao Thị Huệ (Hộ 28)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng, chợ Dục Nội',
    'phone' => '',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  29 => 
  array (
    'stt' => 29,
    'name' => 'Phạm Thị Nga',
    'stall_name' => 'Gian hàng Sữa Chua, Bánh Bao Phạm Thị Nga (Hộ 29)',
    'item_name' => 'sữa chua, bánh bao',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  30 => 
  array (
    'stt' => 30,
    'name' => 'Phạm Thị Hồng Nhung',
    'stall_name' => 'Gian hàng Hoa Quả Phạm Thị Hồng Nhung (Hộ 30)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0397293207',
    'bank_name' => 'MBBank',
    'bank_account' => '0397293207',
    'qr_bin' => '970422',
  ),
  31 => 
  array (
    'stt' => 31,
    'name' => 'Đặng Minh Mạnh',
    'stall_name' => 'Gian hàng Thịt Lợn Đặng Minh Mạnh (Hộ 31)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Mua lợn hơi về thịt',
    'phone' => '',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  32 => 
  array (
    'stt' => 32,
    'name' => 'Hoàng Mạnh Linh',
    'stall_name' => 'Gian hàng Hoa Quả Hoàng Mạnh Linh (Hộ 32)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối Long Biên',
    'phone' => '0936838220',
    'bank_name' => 'Techcombank',
    'bank_account' => '19030000570017',
    'qr_bin' => '970422',
  ),
  33 => 
  array (
    'stt' => 33,
    'name' => 'Nguyễn Quang Chuyền',
    'stall_name' => 'Gian hàng Thịt Nướng Nguyễn Quang Chuyền (Hộ 33)',
    'item_name' => 'thịt nướng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Hà Vĩ',
    'phone' => '0972237683',
    'bank_name' => 'MBBank',
    'bank_account' => '0972237683',
    'qr_bin' => '970422',
  ),
  34 => 
  array (
    'stt' => 34,
    'name' => 'Nguyễn Thanh Mai',
    'stall_name' => 'Gian hàng Trứng Nguyễn Thanh Mai (Hộ 34)',
    'item_name' => 'trứng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vĩnh Ngọc',
    'phone' => '0989751472',
    'bank_name' => 'MBBank',
    'bank_account' => '8883062923',
    'qr_bin' => '970422',
  ),
  35 => 
  array (
    'stt' => 35,
    'name' => 'Nguyễn Thị Phượng',
    'stall_name' => 'Gian hàng Bún, Dưa Cà Nguyễn Thị Phượng (Hộ 35)',
    'item_name' => 'bún, dưa cà',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Mạch Tràng',
    'phone' => '0986595476',
    'bank_name' => 'MBBank',
    'bank_account' => '361505599',
    'qr_bin' => '970422',
  ),
  36 => 
  array (
    'stt' => 36,
    'name' => 'Nguyễn Thị Mai',
    'stall_name' => 'Gian hàng Cá Tươi Nguyễn Thị Mai (Hộ 36)',
    'item_name' => 'cá tươi',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0978197016',
    'bank_name' => 'MBBank',
    'bank_account' => '0978197016',
    'qr_bin' => '970422',
  ),
  37 => 
  array (
    'stt' => 37,
    'name' => 'Ngô Thị Liên',
    'stall_name' => 'Gian hàng Lòng Lợn Ngô Thị Liên (Hộ 37)',
    'item_name' => 'lòng lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '036608168',
    'bank_name' => 'MBBank',
    'bank_account' => '19038338612018',
    'qr_bin' => '970422',
  ),
  38 => 
  array (
    'stt' => 38,
    'name' => 'Trần Thị Mếm',
    'stall_name' => 'Gian hàng Cá Tươi Trần Thị Mếm (Hộ 38)',
    'item_name' => 'cá tươi',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0989641579',
    'bank_name' => 'MBBank',
    'bank_account' => '0989641579',
    'qr_bin' => '970422',
  ),
  39 => 
  array (
    'stt' => 39,
    'name' => 'Vũ Thị Hiền',
    'stall_name' => 'Gian hàng Cua Vũ Thị Hiền (Hộ 39)',
    'item_name' => 'cua',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Thanh Hoá',
    'phone' => '0972166185',
    'bank_name' => 'MBBank',
    'bank_account' => '9030619859999',
    'qr_bin' => '970422',
  ),
  40 => 
  array (
    'stt' => 40,
    'name' => 'Vũ Thanh Tùng',
    'stall_name' => 'Gian hàng Quần Áo Vũ Thanh Tùng (Hộ 40)',
    'item_name' => 'quần áo',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Ninh Hiệp',
    'phone' => '0926893299',
    'bank_name' => 'MBBank',
    'bank_account' => '092689319',
    'qr_bin' => '970422',
  ),
  41 => 
  array (
    'stt' => 41,
    'name' => 'Trần Thị Đỏ',
    'stall_name' => 'Gian hàng Dđồ Ăn Chín: Đậu Nhồi, Thịt Kho Trần Thị Đỏ (Hộ 41)',
    'item_name' => 'dđồ ăn chín: Đậu nhồi, thịt kho',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0339749923',
    'bank_name' => 'MBBank',
    'bank_account' => '86668881993',
    'qr_bin' => '970422',
  ),
  42 => 
  array (
    'stt' => 42,
    'name' => 'Phạm Thị Quy',
    'stall_name' => 'Gian hàng Quần Áo Phạm Thị Quy (Hộ 42)',
    'item_name' => 'quần áo',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0926893198',
    'bank_name' => 'MBBank',
    'bank_account' => '0926893198',
    'qr_bin' => '970422',
  ),
  43 => 
  array (
    'stt' => 43,
    'name' => 'Nguyễn Trí Thực',
    'stall_name' => 'Gian hàng Đậu, Trứng Gà Nguyễn Trí Thực (Hộ 43)',
    'item_name' => 'đậu, trứng gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Ga Đông Anh',
    'phone' => '0365928569',
    'bank_name' => 'MBBank',
    'bank_account' => '2143473113',
    'qr_bin' => '970422',
  ),
  44 => 
  array (
    'stt' => 44,
    'name' => 'Đình Thị Thu',
    'stall_name' => 'Gian hàng Hoa Quả Đình Thị Thu (Hộ 44)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối Long Biên',
    'phone' => '0973166963',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  45 => 
  array (
    'stt' => 45,
    'name' => 'Nguyễn Thị Thu Hồng',
    'stall_name' => 'Gian hàng Giò Chả Nem Nguyễn Thị Thu Hồng (Hộ 45)',
    'item_name' => 'giò chả nem',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Thực phẩm Mạnh Cường',
    'phone' => '0982447428',
    'bank_name' => 'MBBank',
    'bank_account' => '104866284663',
    'qr_bin' => '970422',
  ),
  46 => 
  array (
    'stt' => 46,
    'name' => 'Nguyễn Thị Vân',
    'stall_name' => 'Gian hàng Rau Củ Quả Nguyễn Thị Vân (Hộ 46)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Kim',
    'phone' => '0987718937',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  47 => 
  array (
    'stt' => 47,
    'name' => 'Nguyễn Thị Huệ',
    'stall_name' => 'Gian hàng Rau Củ Quả Nguyễn Thị Huệ (Hộ 47)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0385269548',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  48 => 
  array (
    'stt' => 48,
    'name' => 'Nguyễn Thị Hoàn',
    'stall_name' => 'Gian hàng Giò Chả Nguyễn Thị Hoàn (Hộ 48)',
    'item_name' => 'giò chả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Thực phẩm Mạnh Cường',
    'phone' => '0986895915',
    'bank_name' => 'MBBank',
    'bank_account' => '8889908011981',
    'qr_bin' => '970422',
  ),
  49 => 
  array (
    'stt' => 49,
    'name' => 'Khang Thị Hải',
    'stall_name' => 'Gian hàng Giò Chả Khang Thị Hải (Hộ 49)',
    'item_name' => 'giò chả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '0353273378',
    'bank_name' => 'MBBank',
    'bank_account' => '691978',
    'qr_bin' => '970422',
  ),
  50 => 
  array (
    'stt' => 50,
    'name' => 'Nguyễn Thị Liễu',
    'stall_name' => 'Gian hàng Lòng Lợn Chín Nguyễn Thị Liễu (Hộ 50)',
    'item_name' => 'lòng lợn chín',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ trung tâm Đông Anh',
    'phone' => '0983393697',
    'bank_name' => 'MBBank',
    'bank_account' => '000105874074501',
    'qr_bin' => '970422',
  ),
  51 => 
  array (
    'stt' => 51,
    'name' => 'Nguyễn Thị Miên',
    'stall_name' => 'Gian hàng Thịt Lợn Nguyễn Thị Miên (Hộ 51)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Lò mổ Thư Lâm',
    'phone' => '035820811',
    'bank_name' => 'MBBank',
    'bank_account' => '21410003880643',
    'qr_bin' => '970422',
  ),
  52 => 
  array (
    'stt' => 52,
    'name' => 'Phạm Thị Lợi',
    'stall_name' => 'Gian hàng Thịt Lợn Phạm Thị Lợi (Hộ 52)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Lò mổ Nguyễn Hữu Chương - Việt Hùng - Đông Anh',
    'phone' => '0365971914',
    'bank_name' => 'MBBank',
    'bank_account' => '9365971914',
    'qr_bin' => '970422',
  ),
  53 => 
  array (
    'stt' => 53,
    'name' => 'Cao Thị Hoa',
    'stall_name' => 'Gian hàng Thịt Lợn Cao Thị Hoa (Hộ 53)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Lò mổ Thư Lâm',
    'phone' => '0358068290',
    'bank_name' => 'MBBank',
    'bank_account' => '0358068290',
    'qr_bin' => '970422',
  ),
  54 => 
  array (
    'stt' => 54,
    'name' => 'Hoàng Thị Minh',
    'stall_name' => 'Gian hàng Sáo Bò Hoàng Thị Minh (Hộ 54)',
    'item_name' => 'sáo bò',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ trung tâm Đông Anh',
    'phone' => '0394874996',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  55 => 
  array (
    'stt' => 55,
    'name' => 'Đặng Thị Dung',
    'stall_name' => 'Gian hàng Rau Đặng Thị Dung (Hộ 55)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '03367386341',
    'bank_name' => 'MBBank',
    'bank_account' => '00883671486',
    'qr_bin' => '970422',
  ),
  56 => 
  array (
    'stt' => 56,
    'name' => 'Ngô Thị Xuyến',
    'stall_name' => 'Gian hàng Thịt Lợn Ngô Thị Xuyến (Hộ 56)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Xuân Nộn - Thư Lâm',
    'phone' => '0961237712',
    'bank_name' => 'MBBank',
    'bank_account' => '9982370893',
    'qr_bin' => '970422',
  ),
  57 => 
  array (
    'stt' => 57,
    'name' => 'Nguyễn Thị Diệu',
    'stall_name' => 'Gian hàng Thịt Bò, Sáo Bò Nguyễn Thị Diệu (Hộ 57)',
    'item_name' => 'thịt bò, sáo bò',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối',
    'phone' => '03399444218',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  58 => 
  array (
    'stt' => 58,
    'name' => 'Trần Thị Tỵ',
    'stall_name' => 'Gian hàng Tôm Trần Thị Tỵ (Hộ 58)',
    'item_name' => 'tôm',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0399314927',
    'bank_name' => 'MBBank',
    'bank_account' => '10460551459',
    'qr_bin' => '970422',
  ),
  59 => 
  array (
    'stt' => 59,
    'name' => 'Nguyễn Thị Huyền',
    'stall_name' => 'Gian hàng Thịt Bò, Sáo Bò Nguyễn Thị Huyền (Hộ 59)',
    'item_name' => 'thịt bò, sáo bò',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Hải Bối',
    'phone' => '0364767566',
    'bank_name' => 'BIDV',
    'bank_account' => '2140003902185',
    'qr_bin' => '970418',
  ),
  60 => 
  array (
    'stt' => 60,
    'name' => 'Trần Thị Tươi',
    'stall_name' => 'Gian hàng Thịt Lợn Trần Thị Tươi (Hộ 60)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Kim',
    'phone' => '0377857225',
    'bank_name' => 'MB Bank',
    'bank_account' => '0377857225',
    'qr_bin' => '970422',
  ),
  61 => 
  array (
    'stt' => 61,
    'name' => 'Nguyễn Thị Thanh',
    'stall_name' => 'Gian hàng Cá Tươi Nguyễn Thị Thanh (Hộ 61)',
    'item_name' => 'cá tươi',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0379766914',
    'bank_name' => 'BIDV',
    'bank_account' => '88030667880',
    'qr_bin' => '970418',
  ),
  62 => 
  array (
    'stt' => 62,
    'name' => 'Phạm Thị Nhi',
    'stall_name' => 'Gian hàng Tôm Phạm Thị Nhi (Hộ 62)',
    'item_name' => 'tôm',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0394631996',
    'bank_name' => 'MBBank',
    'bank_account' => '3394631996',
    'qr_bin' => '970422',
  ),
  63 => 
  array (
    'stt' => 63,
    'name' => 'Lê Thị Biên',
    'stall_name' => 'Gian hàng Cá, Ngao, Ếch Lê Thị Biên (Hộ 63)',
    'item_name' => 'cá, ngao, ếch',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0396161408',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  64 => 
  array (
    'stt' => 64,
    'name' => 'Ngô Thị Khánh',
    'stall_name' => 'Gian hàng Cá, Ếch, Ốc Ngô Thị Khánh (Hộ 64)',
    'item_name' => 'cá, ếch, ốc',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0867411983',
    'bank_name' => 'BIDV',
    'bank_account' => '8832917023',
    'qr_bin' => '970418',
  ),
  65 => 
  array (
    'stt' => 65,
    'name' => 'Trương Thị Hải',
    'stall_name' => 'Gian hàng Cá Tươi, Ngao Trương Thị Hải (Hộ 65)',
    'item_name' => 'cá tươi, ngao',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0343530478',
    'bank_name' => 'BIDV',
    'bank_account' => '211410003813746',
    'qr_bin' => '970418',
  ),
  66 => 
  array (
    'stt' => 66,
    'name' => 'Đỗ Thị Dậu',
    'stall_name' => 'Gian hàng Thịt Gà Đỗ Thị Dậu (Hộ 66)',
    'item_name' => 'thịt gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Thái Nguyên',
    'phone' => '0399698915',
    'bank_name' => 'VCB',
    'bank_account' => '1034858794',
    'qr_bin' => '970436',
  ),
  67 => 
  array (
    'stt' => 67,
    'name' => 'Nguyễn Thị Thu Phương',
    'stall_name' => 'Gian hàng Hàng Ăn Chín Đậu, Thịt Kho Nguyễn Thị Thu Phương (Hộ 67)',
    'item_name' => 'hàng ăn chín đậu, thịt kho',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0977136799',
    'bank_name' => 'MB Bank',
    'bank_account' => '0310102934007',
    'qr_bin' => '970422',
  ),
  68 => 
  array (
    'stt' => 68,
    'name' => 'Nguyễn Thị Tâm',
    'stall_name' => 'Gian hàng Đậu Phụ Nguyễn Thị Tâm (Hộ 68)',
    'item_name' => 'đậu phụ',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0866163994',
    'bank_name' => 'VP Bank',
    'bank_account' => '0866163994',
    'qr_bin' => '970432',
  ),
  69 => 
  array (
    'stt' => 69,
    'name' => 'Nguyễn Thị Thanh',
    'stall_name' => 'Gian hàng Chim Cút Nguyễn Thị Thanh (Hộ 69)',
    'item_name' => 'chim cút',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Xã Thư Lâm',
    'phone' => '039770656',
    'bank_name' => 'MBBank',
    'bank_account' => '33977056',
    'qr_bin' => '970422',
  ),
  70 => 
  array (
    'stt' => 70,
    'name' => 'Cao Thị Nhạn',
    'stall_name' => 'Gian hàng Hoa Tươi Cao Thị Nhạn (Hộ 70)',
    'item_name' => 'hoa tươi',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0365978693',
    'bank_name' => 'Vietinbank',
    'bank_account' => '100878000359',
    'qr_bin' => '970415',
  ),
  71 => 
  array (
    'stt' => 71,
    'name' => 'Bùi Thị Huyền',
    'stall_name' => 'Gian hàng Hoa Quả Bùi Thị Huyền (Hộ 71)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0962531347',
    'bank_name' => 'MB Bank',
    'bank_account' => '0962531347',
    'qr_bin' => '970422',
  ),
  72 => 
  array (
    'stt' => 72,
    'name' => 'Trần Thị Tê',
    'stall_name' => 'Gian hàng Thịt Gà Trần Thị Tê (Hộ 72)',
    'item_name' => 'thịt gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn',
    'phone' => '0346603224',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  73 => 
  array (
    'stt' => 73,
    'name' => 'Công Thị Thơ',
    'stall_name' => 'Gian hàng Quần Áo Công Thị Thơ (Hộ 73)',
    'item_name' => 'quần áo',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Đồng Xuân',
    'phone' => '0346073088',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  74 => 
  array (
    'stt' => 74,
    'name' => 'Trần Lệ Mỹ',
    'stall_name' => 'Gian hàng Thịt Nướng Trần Lệ Mỹ (Hộ 74)',
    'item_name' => 'thịt nướng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0983597366',
    'bank_name' => 'Vietinbank',
    'bank_account' => '104883640829',
    'qr_bin' => '970415',
  ),
  75 => 
  array (
    'stt' => 75,
    'name' => 'Phạm Thị Thoa',
    'stall_name' => 'Gian hàng Rau Phạm Thị Thoa (Hộ 75)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Mạch Tràng',
    'phone' => '0353879680',
    'bank_name' => 'VP Bank',
    'bank_account' => '0353879680',
    'qr_bin' => '970432',
  ),
  76 => 
  array (
    'stt' => 76,
    'name' => 'Nguyễn Thị Huệ',
    'stall_name' => 'Gian hàng Rau Củ Quả Nguyễn Thị Huệ (Hộ 76)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0385269548',
    'bank_name' => 'MB Bank',
    'bank_account' => '0385269548',
    'qr_bin' => '970422',
  ),
  77 => 
  array (
    'stt' => 77,
    'name' => 'Nguyễn Hữu Tuyến',
    'stall_name' => 'Gian hàng Rau Củ Quả Nguyễn Hữu Tuyến (Hộ 77)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0985173034',
    'bank_name' => 'Vietinbank',
    'bank_account' => '0368660828',
    'qr_bin' => '970415',
  ),
  78 => 
  array (
    'stt' => 78,
    'name' => 'Trần Thị Hà',
    'stall_name' => 'Gian hàng Hoa Quả Trần Thị Hà (Hộ 78)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Long Biên',
    'phone' => '0362775306',
    'bank_name' => 'Techcombank',
    'bank_account' => '3362775306',
    'qr_bin' => '970422',
  ),
  79 => 
  array (
    'stt' => 79,
    'name' => 'Dương Văn Phi',
    'stall_name' => 'Gian hàng Thịt Nướng Dương Văn Phi (Hộ 79)',
    'item_name' => 'thịt nướng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Ngọc Thuỵ - Long Biên',
    'phone' => '0978026537',
    'bank_name' => 'MB Bank',
    'bank_account' => '820128208001',
    'qr_bin' => '970422',
  ),
  80 => 
  array (
    'stt' => 80,
    'name' => 'Ngô Thị Qui',
    'stall_name' => 'Gian hàng Thịt Nướng Ngô Thị Qui (Hộ 80)',
    'item_name' => 'thịt nướng',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '0349410809',
    'bank_name' => 'BIDV',
    'bank_account' => '21410003440782',
    'qr_bin' => '970418',
  ),
  81 => 
  array (
    'stt' => 81,
    'name' => 'Chu Thị Thanh Hoa',
    'stall_name' => 'Gian hàng Đồ Ăn Chín Ngô, Củ, Tôm Cá Chu Thị Thanh Hoa (Hộ 81)',
    'item_name' => 'đồ ăn chín ngô, củ, tôm cá',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0344658796',
    'bank_name' => 'MB Bank',
    'bank_account' => '9991234545678',
    'qr_bin' => '970422',
  ),
  82 => 
  array (
    'stt' => 82,
    'name' => 'Đình Thị Hằng',
    'stall_name' => 'Gian hàng Thịt Gà Đình Thị Hằng (Hộ 82)',
    'item_name' => 'thịt gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0327313406',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  83 => 
  array (
    'stt' => 83,
    'name' => 'Đặng Thị Thái',
    'stall_name' => 'Gian hàng Thịt Gà Đặng Thị Thái (Hộ 83)',
    'item_name' => 'thịt gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Thư Lâm',
    'phone' => '0983572129',
    'bank_name' => 'MBBank',
    'bank_account' => '1919618386',
    'qr_bin' => '970422',
  ),
  84 => 
  array (
    'stt' => 84,
    'name' => 'Chí Thị Mùa',
    'stall_name' => 'Gian hàng Thịt Bò Chí Thị Mùa (Hộ 84)',
    'item_name' => 'thịt bò',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0976965568',
    'bank_name' => 'MBBank',
    'bank_account' => '05101979668',
    'qr_bin' => '970422',
  ),
  85 => 
  array (
    'stt' => 85,
    'name' => 'Nguyễn Thị Công Hoa',
    'stall_name' => 'Gian hàng Đồ Ăn Chín Ngô, Củ, Tôm, Nem Nguyễn Thị Công Hoa (Hộ 85)',
    'item_name' => 'đồ ăn chín ngô, củ, tôm, nem',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó, chợ Vân Trì',
    'phone' => '0975159242',
    'bank_name' => 'MBBank',
    'bank_account' => '0975159242',
    'qr_bin' => '970422',
  ),
  86 => 
  array (
    'stt' => 86,
    'name' => 'Nguyễn Thị Thanh',
    'stall_name' => 'Gian hàng Hoa Quả Nguyễn Thị Thanh (Hộ 86)',
    'item_name' => 'hoa quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Yên Thụ',
    'phone' => '0388645522',
    'bank_name' => 'MBBank',
    'bank_account' => '19036507129019',
    'qr_bin' => '970422',
  ),
  87 => 
  array (
    'stt' => 87,
    'name' => 'Phạm Thị Châm',
    'stall_name' => 'Gian hàng Thịt Bò Phạm Thị Châm (Hộ 87)',
    'item_name' => 'thịt bò',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối',
    'phone' => '0984141566',
    'bank_name' => 'MBBank',
    'bank_account' => '0396202228',
    'qr_bin' => '970422',
  ),
  88 => 
  array (
    'stt' => 88,
    'name' => 'Ngô Thị Định',
    'stall_name' => 'Gian hàng Trứng Vịt, Gà Ngô Thị Định (Hộ 88)',
    'item_name' => 'trứng vịt, gà',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '037948976',
    'bank_name' => 'MBBank',
    'bank_account' => '037948976',
    'qr_bin' => '970422',
  ),
  89 => 
  array (
    'stt' => 89,
    'name' => 'Hoàng Thị Hiền',
    'stall_name' => 'Gian hàng Vịt Quay Hoàng Thị Hiền (Hộ 89)',
    'item_name' => 'vịt quay',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối',
    'phone' => '0983523349',
    'bank_name' => 'MBBank',
    'bank_account' => '098323349',
    'qr_bin' => '970422',
  ),
  90 => 
  array (
    'stt' => 90,
    'name' => 'Nguyễn Thị Hiệu',
    'stall_name' => 'Gian hàng Hành Tỏi Khô Nguyễn Thị Hiệu (Hộ 90)',
    'item_name' => 'hành tỏi khô',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0968955702',
    'bank_name' => 'MBBank',
    'bank_account' => '030302626',
    'qr_bin' => '970422',
  ),
  91 => 
  array (
    'stt' => 91,
    'name' => 'Nguyễn Thị Hằng',
    'stall_name' => 'Gian hàng Thịt Gà, Vịt Nguyễn Thị Hằng (Hộ 91)',
    'item_name' => 'thịt gà, vịt',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn - Bắc Ninh',
    'phone' => '0348114381',
    'bank_name' => 'BIDV',
    'bank_account' => '8860192752',
    'qr_bin' => '970418',
  ),
  92 => 
  array (
    'stt' => 92,
    'name' => 'Nguyễn Trọng Thắng',
    'stall_name' => 'Gian hàng Thịt Chó Nguyễn Trọng Thắng (Hộ 92)',
    'item_name' => 'thịt chó',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Thanh Hoá',
    'phone' => '0983219375',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  93 => 
  array (
    'stt' => 93,
    'name' => 'Công Thị Tiếu',
    'stall_name' => 'Gian hàng Rau Công Thị Tiếu (Hộ 93)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng',
    'phone' => '',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  94 => 
  array (
    'stt' => 94,
    'name' => 'Vũ Thị Hiền',
    'stall_name' => 'Gian hàng Bách Hóa Tổng Hợp Vũ Thị Hiền (Hộ 94)',
    'item_name' => 'Bách hóa tổng hợp',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Thanh Hoá',
    'phone' => '0972166185',
    'bank_name' => 'MBBank',
    'bank_account' => '9030619859999',
    'qr_bin' => '970422',
  ),
  95 => 
  array (
    'stt' => 95,
    'name' => 'Ngô Thị Lụa',
    'stall_name' => 'Gian hàng Rau Ngô Thị Lụa (Hộ 95)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0982825093',
    'bank_name' => 'MBBank',
    'bank_account' => '51820556868',
    'qr_bin' => '970422',
  ),
  96 => 
  array (
    'stt' => 96,
    'name' => 'Trần Văn Phương',
    'stall_name' => 'Gian hàng Vịt Quay Trần Văn Phương (Hộ 96)',
    'item_name' => 'vịt quay',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ đầu mối Bắc Thăng Long',
    'phone' => '0962140213',
    'bank_name' => 'MB bank',
    'bank_account' => '0962140213',
    'qr_bin' => '970422',
  ),
  97 => 
  array (
    'stt' => 97,
    'name' => 'Nguyễn Thị Dung',
    'stall_name' => 'Gian hàng Hoa Củ Quả Nguyễn Thị Dung (Hộ 97)',
    'item_name' => 'hoa củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Vân Trì',
    'phone' => '0384453763',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  98 => 
  array (
    'stt' => 98,
    'name' => 'Nguyễn Thị Oanh',
    'stall_name' => 'Gian hàng Ốc Và Ngao Nguyễn Thị Oanh (Hộ 98)',
    'item_name' => 'ốc và ngao',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Từ Sơn - Bắc Ninh',
    'phone' => '0343016467',
    'bank_name' => 'MB Bank',
    'bank_account' => '0343016467',
    'qr_bin' => '970422',
  ),
  99 => 
  array (
    'stt' => 99,
    'name' => 'Nguyễn Đức Hưng',
    'stall_name' => 'Gian hàng Thịt Chó Sống Nguyễn Đức Hưng (Hộ 99)',
    'item_name' => 'thịt chó sống',
    'price' => 0,
    'unit' => NULL,
    'origin' => '',
    'phone' => '0359702259',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  100 => 
  array (
    'stt' => 100,
    'name' => 'Trần Thị Thanh Dung',
    'stall_name' => 'Gian hàng Đỗ Lạc Trần Thị Thanh Dung (Hộ 100)',
    'item_name' => 'đỗ lạc',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Bắc Giang',
    'phone' => '0986491258',
    'bank_name' => 'BIDV',
    'bank_account' => '2143813612',
    'qr_bin' => '970418',
  ),
  101 => 
  array (
    'stt' => 101,
    'name' => 'Khang Thị Vân',
    'stall_name' => 'Gian hàng Rau Khang Thị Vân (Hộ 101)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng',
    'phone' => '0387011304',
    'bank_name' => 'CN đầu tư phát triển',
    'bank_account' => '2203331331',
    'qr_bin' => '970418',
  ),
  102 => 
  array (
    'stt' => 102,
    'name' => 'Phạm Thị Sáu',
    'stall_name' => 'Gian hàng Rau Phạm Thị Sáu (Hộ 102)',
    'item_name' => 'rau',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng',
    'phone' => '0966947812',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  103 => 
  array (
    'stt' => 103,
    'name' => 'Nguyễn Thị Nhiên',
    'stall_name' => 'Gian hàng Rau Quả Nguyễn Thị Nhiên (Hộ 103)',
    'item_name' => 'rau quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Nhà trồng, chợ Dục Nội',
    'phone' => '0383901235',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  104 => 
  array (
    'stt' => 104,
    'name' => 'Nguyễn Thị Thuý Vân',
    'stall_name' => 'Gian hàng Đồ Ăn Chín, Cá Thịt Kho Nguyễn Thị Thuý Vân (Hộ 104)',
    'item_name' => 'đồ ăn chín, cá thịt kho',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Dục Nội',
    'phone' => '0978760576',
    'bank_name' => 'Techcombank',
    'bank_account' => '04113283337513',
    'qr_bin' => '970422',
  ),
  105 => 
  array (
    'stt' => 105,
    'name' => 'Nguyễn Công Nhiễu',
    'stall_name' => 'Gian hàng Thịt Lợn Nguyễn Công Nhiễu (Hộ 105)',
    'item_name' => 'thịt lợn',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Lò mổ Tiến Đạo - xã Thư Lâm',
    'phone' => '0974010894',
    'bank_name' => 'MBBank',
    'bank_account' => '8882016730',
    'qr_bin' => '970422',
  ),
  106 => 
  array (
    'stt' => 106,
    'name' => 'Đình Thị Phương',
    'stall_name' => 'Gian hàng Rau Củ Quả Đình Thị Phương (Hộ 106)',
    'item_name' => 'rau củ quả',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Chợ Tó',
    'phone' => '0389253416',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
  107 => 
  array (
    'stt' => 107,
    'name' => 'Vũ Văn Phương',
    'stall_name' => 'Gian hàng Đậu Phụ Vũ Văn Phương (Hộ 107)',
    'item_name' => 'đậu phụ',
    'price' => 0,
    'unit' => NULL,
    'origin' => 'Việt Nam',
    'phone' => '0963915240',
    'bank_name' => NULL,
    'bank_account' => NULL,
    'qr_bin' => NULL,
  ),
);

        // Xóa toàn bộ sạp cũ thuộc Chợ Dày Da để nạp lại chuẩn xác 107 sạp
        DB::table('ocop_products')->where('eatery_id', $marketId)->delete();

        foreach ($merchants as $stt => $m) {
            $stallId = 2580 + $stt;
            $email = "seller.dayDa.{$stt}@foodmap.vn";
            $phone = $m['phone'] ?: '';
            $name = $m['name'];
            $stallName = $m['stall_name'];

            // Xử lý tạo QR VietQR
            $qrUrl = null;
            if (!empty($m['bank_account']) && !empty($m['qr_bin'])) {
                $qrUrl = "https://api.vietqr.io/image/{$m['qr_bin']}-{$m['bank_account']}-compact.png?accountName=" . urlencode($name);
            }

            // Xử lý tạo / cập nhật User
            $user = User::where('email', $email)->first();
            if (!$user) {
                $userId = DB::table('users')->insertGetId([
                    'name' => $name,
                    'email' => $email,
                    'phone' => $phone ?: 'Cần cập nhật thông tin',
                    'password' => Hash::make('123456@'),
                    'role' => 'seller',
                    'status' => 'active',
                    'eatery_id' => $marketId,
                    'stall_id' => $stallId,
                    'bank_name' => $m['bank_name'],
                    'bank_account' => $m['bank_account'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            } else {
                $user->update([
                    'name' => $name,
                    'email' => $email,
                    'phone' => $phone ?: 'Cần cập nhật thông tin',
                    'role' => 'seller',
                    'status' => 'active',
                    'eatery_id' => $marketId,
                    'stall_id' => $stallId,
                    'bank_name' => $m['bank_name'],
                    'bank_account' => $m['bank_account'],
                ]);
                $userId = $user->id;
            }

            // Xử lý tạo Gian hàng
            $descParts = [];
            if (!empty($m['origin'])) $descParts[] = "Nguồn gốc: {$m['origin']}";
            $descParts[] = "Hộ kinh doanh tại Chợ Dày Da, Việt Hùng";
            $desc = implode('. ', $descParts) . '.';

            DB::table('ocop_products')->insert([
                'id' => $stallId,
                'eatery_id' => $marketId,
                'user_id' => $userId,
                'stall_name' => $stallName,
                'name' => $m['item_name'],
                'seller_name' => $name,
                'seller_phone' => $phone ?: 'Cần cập nhật thông tin',
                'price' => $m['price'],
                'unit' => $m['unit'],
                'description' => $desc,
                'bank_name' => $m['bank_name'],
                'bank_account' => $m['bank_account'],
                'bank_holder' => !empty($m['bank_account']) ? $name : null,
                'qr_code_path' => $qrUrl,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
    }
};
